[package]
name = "uni-snd"
version = "0.1.0"
authors = ["jice <jice.nospam@gmail.com>"]
description = "Unrust low level native/wasm compatibility layer for sound output"
license = "MIT"
documentation = "https://docs.rs/uni-snd"
repository = "https://github.com/unrust/uni-snd"
keywords = ["sound", "wasm"]

[dependencies]
uni-app="0.1.*"
[target.wasm32-unknown-unknown.dependencies]
stdweb =  "0.4.8"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal="0.8"